### PR TITLE
[2.x] CheckoutAgreements from db (eloquent model)

### PR DESCRIPTION
**Pull request by Jade-GG**
The checkoutagreements were pulled from graphql before, but these are very easily directly retrieved from the database. With this PR I've made an eloquent model for the checkoutagreements and implemented them.

I had to, for some reason, fix the lateral join thing for this. I'm fairly confident I remember it working fine before so I'm not sure what's changed, but this contains a fix for that.

### CODE REVIEW

**Comment by royduin** [comment]
Looking good to me, let's wait for @indykoning as final review.

**Review by royduin — APPROVED** [review]

**Review by indykoning — DISMISSED** [review]

**Comment by royduin** [comment]
Conflict @Jade-GG 😇

**Comment by Jade-GG** [comment]
> Conflict @Jade-GG 😇

fixed :)

**Comment by Jade-GG** [comment]
> Conflict @Jade-GG 😇

Fixed 😇

**Pull request merged**
