### PR TITLE
Hide content blocks on mobile & change mobile logo

### PR DESCRIPTION
**Pull request by Jade-GG**
Hide them because they just don't fit

### CODE REVIEW

**Comment by royduin** [comment]
The tests are failing 😇

**Comment by Jade-GG** [comment]
Not sure why it still fails to find the text "Men Tops Collection" when it's literally on the page...

**Comment by royduin** [comment]
Download the artifact to debug ;)

**Comment by Jade-GG** [comment]
Tests are successful now :)

**Pull request merged**
