### PR TITLE
Use script to get the positions from the flattened type

### PR DESCRIPTION
**Pull request by Jade-GG**
Supersedes #427.

We use a script here because the position from the flattened type, for some reason, cannot be implicitly cast to a number type *even though that's literally what it contains if you retrieve it directly from the index*.

By using a script, we can directly parse (not explicitly cast, that also doesn't work) it into a number. ES scripts get cached so this doesn't cause any sort of noticeable performance hit.

### CODE REVIEW

**Review by jbclaudio — APPROVED** [review]

**Comment by royduin** [comment]
So this is THE fix? We don't need any monkey patches?

**Comment by Jade-GG** [comment]
> So this is THE fix? We don't need any monkey patches?

Correct, it's not pretty but it works flawlessly.

**Review by indykoning — APPROVED** [review]

**Comment by royduin** [comment]
Please create another PR for master 😇

**Comment by BobWez98** [comment]
Can be closed because of #467

**Pull request closed without merging**
