### PR TITLE
Removed classes from base button | Placed paddings on buttons where needed

### PR DESCRIPTION
**Pull request by Roene-JustBetter**
We don't need al of this classes on the button. 

- I removed classes from the base button that we don't need.
- Placed paddings on the buttons where we need it.

### CODE REVIEW

**Comment by Roene-JustBetter** [comment]
@jordythevulder @JimmyHoenderdaal

**Review by JimmyHoenderdaal — APPROVED** [review]

**Comment by jordythevulder** [comment]
Looks good! It has my approval

**Comment by indykoning** [comment]
What is the impact of this? It looks to me like it isn't breaking as long as you've been using the normal button components.
Do we often use the base button?

**Review by indykoning — DISMISSED** [review]

**Comment by royduin** [comment]
What's changed visually?

**Comment by Roene-JustBetter** [comment]
> What's changed visually?

Nothing changed visually. What I did is removed & replaced classes from the button/base to keep this clean and placed classes on buttons where it needed. For example not all buttons need the same padding (buttons used for slider) and only the outline button needs a border instead of every button.

**Comment by royduin** [comment]
Did you test this? I'm reverting it with #499 as this is the result now:

image

**Pull request merged**
