### PR TITLE
[3.x] Implement PHPStan level 1

### PR DESCRIPTION
**Pull request by Jade-GG**

### CODE REVIEW

**Review by indykoning — DISMISSED** [review]

**Comment by royduin** [comment]
Can we skip the docblocks?

**Comment by Jade-GG** [comment]
> Can we skip the docblocks?

We can't skip these without either getting rid of phpstan entirely, or having a ton of different ignores.

**Comment by Jade-GG** [comment]
> Can we skip the docblocks?

Done :)

**Comment by royduin** [comment]
Thanks!! 💯

**Pull request merged**
