### PR TITLE
[3.x] Use correct object structure in postcss config

### PR DESCRIPTION
**Pull request by Jade-GG**

### CODE REVIEW

**Review by indykoning — APPROVED** [review]

**Comment by royduin** [comment]
What does it fix? Do you have a better description I can use for the commit message.

**Comment by Jade-GG** [comment]
Yes, this is related to the vite update that changed everything to ESM modules, but this file was updated incorrectly. So for a description, something like:

Use correct object structure in postcss config

**Comment by royduin** [comment]
This also needs be fixed in v2 right?

**Comment by Jade-GG** [comment]
> This also needs be fixed in v2 right?

Ah you're right, I thought the branch split was from before this update. I'll make a PR.

**Pull request merged**
