### PR TITLE
Fix undefined message when an error occurs when placing order

### PR DESCRIPTION
**Pull request by indykoning**

### CODE REVIEW

**Comment by royduin** [comment]
This is v3 only? As it's going to master now.

**Comment by indykoning** [comment]
Checkout.vue will no longer exist in V3, nor will it use REST so it's only relevant for V2
i've changed the branches

**Comment by indykoning** [comment]
I'm going to recreate this branch on V2

**Comment by indykoning** [comment]
See: https://github.com/rapidez/core/pull/599

**Pull request closed without merging**
